<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class MovementTypeSeeder extends AbstractSeed
{
    const TWO_DAYS_MILLIS = 2 * 24 * 60 * 60 * 1000;

    public function run(): void
    {
        $data = [
            [
                'name' => 'Transferência entre contas (Enviar)',
                'description' => 'Usuário Pagstar realizou uma transferência a outro usuário Pagstar',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 6.99,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Transferência entre contas (Recebimento)',
                'description' => 'Usuário Pagstar recebeu uma transferência de outro usuário Pagstar',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Transferência externa (Conta Bancária)',
                'description' => 'Usuário Pagstar realizou uma transferência para uma conta bancária externa',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 6.99,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Transferência externa (PIX)',
                'description' => 'Usuário Pagstar realizou uma transferência para uma chave PIX externa',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento (Saldo)',
                'description' => 'Usuário faz um pagamento para o parceiro com saldo da carteira',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento (PIX)',
                'description' => 'Usuário faz um pagamento para um parceiro com Pix',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento (PIX Anônimo)',
                'description' => 'Usuário faz um pagamento para o parceiro com cartão de crédito',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento (Cartão de crédito)',
                'description' => 'Usuário faz um pagamento para o parceiro com Cashback',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 1,
                'fee' => 2.2,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento (Cashback)',
                'description' => 'Usuário faz um pagamento para o parceiro com Cashback',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Cobrança',
                'description' => 'Usuário realiza o envio de uma cobrança para outro usuário',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Dívida',
                'description' => 'Dívida de um usuário para outro usuário',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Depósito (Boleto)',
                'description' => 'Adição de saldo com boleto',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 1.99,
                'fee' => 1,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Depósito (TED)',
                'description' => 'Adição de saldo via Transferência',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Depósito (Cartão de Crédito)',
                'description' => 'Adição de saldo com cartão de crédito',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 3.99,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Depósito (PIX)',
                'description' => 'Adição de saldo com Pix',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Saque (Bancário)',
                'description' => 'Solicitação de saque do usuário para uma conta externa',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 6.99,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Saque (Dinheiro)',
                'description' => 'Solicitação de saque do usuário em um Caixa 24hs',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 7.99,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 10,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Saque (PIX)',
                'description' => 'Solicitação de saque do usuário utilizando o PIX',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 10,
                'max_value' => 10000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 10,
                'max_value_per_month' => 50000,
            ],
            [
                'name' => 'Remessa',
                'description' => 'Parceiro solicita um saque internacional',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Liquidação',
                'description' => 'Liquidação da carteira, saque nacional',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Bônus',
                'description' => 'Recompensa enviada do Adm para o usuário',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Bônus (Convite)',
                'description' => 'Usuário Pagstar recebe bônus ao ter um convidado dele depositar o valor do convite',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Cashback',
                'description' => 'Usuário realiza uma compra, ou pagamento, e recebe parte do dinheiro de volta',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Resgate',
                'description' => 'Transferência para o usuário de uma solicitação de saque no site do parceiro',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
            [
                'name' => 'Pagamento de conta',
                'description' => 'Efetua o pagamento de uma conta a partir de um boleto',
                'expiry_time_ms' => self::TWO_DAYS_MILLIS,
                'fare' => 0,
                'fee' => 0,
                'min_value' => 1000,
                'max_value' => 500000,
                'max_quantity_per_day' => 3,
                'max_value_per_day' => 10000,
                'max_quantity_per_month' => 200,
                'max_value_per_month' => 500000,
            ],
        ];

        $this->table('movement_types')->truncate();

        $this->table('movement_types')
            ->insert($data)
            ->saveData();
    }
}
